### ISSUE TITLE
What is a Git Repo

### ISSUE THREAD

**Issue by dinis-cruz-gw** [filetrust/docker-sdk#5]
asked by Nick

**Comment by npb654** [comment]
GitHub is a code hosting platform for version control and collaboration. It lets you and others work together on projects from anywhere.

This tutorial teaches you GitHub essentials like repositories, branches, commits, and Pull Requests. You’ll create your own Hello World repository and learn GitHub’s Pull Request workflow, a popular way to create and review code.
